export const colors = {
  "Red": "#FF0000",
  "OrangeRed": "#FF4500",
  "DarkOrange": "#FF8C00",
  "Orange": "#FFA500",
  "Gold": "#FFD700",
  "Yellow": "#FFFF00",
  "LemonChiffon": "#FFFACD",
  "LightYellow": "#FFFFE0",
  "PaleGoldenrod": "#EEE8AA",
  "Khaki": "#F0E68C",
  "DarkKhaki": "#BDB76B",
  "Olive": "#808000",
  "YellowGreen": "#9ACD32",
  "LimeGreen": "#32CD32",
  "Lime": "#00FF00",
  "Green": "#008000",
  "ForestGreen": "#228B22",
  "DarkGreen": "#006400",
  "SeaGreen": "#2E8B57",
  "MediumSeaGreen": "#3CB371",
  "MediumAquamarine": "#66CDAA",
  "MediumTurquoise": "#48D1CC",
  "Turquoise": "#40E0D0",
  "LightSeaGreen": "#20B2AA",
  "CadetBlue": "#5F9EA0",
  "SteelBlue": "#4682B4",
  "LightSteelBlue": "#B0C4DE",
  "PowderBlue": "#B0E0E6",
  "LightBlue": "#ADD8E6",
  "SkyBlue": "#87CEEB",
  "DeepSkyBlue": "#00BFFF",
  "DodgerBlue": "#1E90FF",
  "RoyalBlue": "#4169E1",
  "Blue": "#0000FF",
  "MediumBlue": "#0000CD",
  "DarkBlue": "#00008B",
  "Navy": "#000080",
  "MidnightBlue": "#191970",
  "SlateBlue": "#6A5ACD",
  "MediumSlateBlue": "#7B68EE",
  "DarkSlateBlue": "#483D8B",
  "Purple": "#800080",
  "DarkMagenta": "#8B008B",
  "DarkOrchid": "#9932CC",
  "MediumOrchid": "#BA55D3",
  "Orchid": "#DA70D6",
  "Thistle": "#D8BFD8",
  "Plum": "#DDA0DD",
  "default": "#ccc"
}

export const stateAbbreviation = {
  "Alabama": "AL",
  "Alaska": "AK",
  "Arizona": "AZ",
  "Arkansas": "AR",
  "California": "CA",
  "Colorado": "CO",
  "Connecticut": "CT",
  "Delaware": "DE",
  "Florida": "FL",
  "Georgia": "GA",
  "Hawaii": "HI",
  "Idaho": "ID",
  "Illinois": "IL",
  "Indiana": "IN",
  "Iowa": "IA",
  "Kansas": "KS",
  "Kentucky": "KY",
  "Louisiana": "LA",
  "Maine": "ME",
  "Maryland": "MD",
  "Massachusetts": "MA",
  "Michigan": "MI",
  "Minnesota": "MN",
  "Mississippi": "MS",
  "Missouri": "MO",
  "Montana": "MT",
  "Nebraska": "NE",
  "Nevada": "NV",
  "New Hampshire": "NH",
  "New Jersey": "NJ",
  "New Mexico": "NM",
  "New York": "NY",
  "North Carolina": "NC",
  "North Dakota": "ND",
  "Ohio": "OH",
  "Oklahoma": "OK",
  "Oregon": "OR",
  "Pennsylvania": "PA",
  "Rhode Island": "RI",
  "South Carolina": "SC",
  "South Dakota": "SD",
  "Tennessee": "TN",
  "Texas": "TX",
  "Utah": "UT",
  "Vermont": "VT",
  "Virginia": "VA",
  "Washington": "WA",
  "West Virginia": "WV",
  "Wisconsin": "WI",
  "Wyoming": "WY"
}