steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/carbon-feat-410602/github.com/bradyadger12/keepupmaps_web:latest', '.']
  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/carbon-feat-410602/github.com/bradyadger12/keepupmaps_web:latest']
  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'keepupmaps-web'
      - '--image=gcr.io/carbon-feat-410602/github.com/bradyadger12/keepupmaps_web:latest'
      - '--platform=managed'
      - '--region=us-central1'
options:
  logging:
    # Specify the logs bucket here
    logsBucket: CLOUD_LOGGING_ONLY